import { NgModule } from '@angular/core';
import { PreloadAllModules, RouterModule, Routes } from '@angular/router';
import { EXTENDED_ROUTES } from './commonSRC/customization/psServices/util/common-cust-utils';



const routes: Routes = [
  ...EXTENDED_ROUTES,
  // { path: '', redirectTo: 'omni-login', pathMatch: 'full' },
  { path: 'omni-login', loadChildren: () => import('./pages/omni-login/omni-login.module').then(m => m.OmniLoginPageModule) },
  { path: 'online-registration', loadChildren: () => import('./pages/online-registration/online-registration.module').then(m => m.OnlineRegistrationPageModule) },
  { path: 'change-pin', loadChildren: () => import('./pages/change-pin/change-pin.page.module').then(m => m.ChangePinPageModule) },
  { path: 'change-pass', loadChildren: () => import('./pages/change-pass/change-pass.page.module').then(m => m.ChangePassPageModule) },
  { path: 'forgot-credentials', loadChildren: () => import('./pages/forgot-credentials/forgot-credentials.module').then(m => m.ForgotCredentialsPageModule) },
  { path: 'terms-and-conditions', loadChildren: () => import('./pages/terms-and-conditions/terms-and-conditions.module').then(m => m.TermsAndConditionsPageModule) },
  { path: 'atm-branch-locator', loadChildren: () => import('./pages/atm-and-branch-locator/atm-and-branch-locator.module').then(m => m.AtmAndBranchLocatorPageModule) },
  { path: 'qibla-direction', loadChildren: () => import('./pages/qibla-direction/qibla-direction.module').then(m => m.QiblaDirectionPageModule) },
  { path: 'omni-login-test', loadChildren: () => import('./pages/omni-login/omni-login.module').then(m => m.OmniLoginPageModule), outlet: 'testOutlet' },
  { path: 'financial-calculator', loadChildren: () => import('./pages/financial-calculator/financial-calculator.module').then(m => m.FinancialCalculatorPageModule) },
  { path: 'facility-request', loadChildren: () => import('./pages/facility-request/facility-request.module').then(m => m.FacilityRequestPageModule) },
  { path: 'outward-bills', loadChildren: () => import('./pages/outward-bills/outward-bills.module').then(m => m.OutwardBillsPageModule) },
  { path: 'prayer-time', loadChildren: () => import('./pages/prayer-time/prayer-time.module').then(m => m.PrayerTimePageModule) },
  { path: 'home', loadChildren: () => import('./pages/home/home.module').then(m => m.HomePageModule) },
  { path: 'account-opening', loadChildren: () => import('./pages/account-opening/account-opening.module').then(m => m.AccountOpeningPageModule) },
  { path: 'account-opening-fixed-maturity-account', loadChildren: () => import('./pages/account-opening-fixed-maturity-account/account-opening-fixed-maturity-account.module').then(m => m.AccountOpeningFixedMaturityAccountPageModule) },
  { path: 'bank-local', loadChildren: () => import('./pages/bank-local/bank-local.module').then(m => m.BankLocalPageModule) },
  { path: 'country-local', loadChildren: () => import('./pages/country-local/country-local.module').then(m => m.CountryLocalPageModule) },
  { path: 'international', loadChildren: () => import('./pages/international/international.module').then(m => m.InternationalPageModule) },
  { path: 'debit-card-request', loadChildren: () => import('./pages/debit-card-request/debit-card-request.module').then(m => m.DebitCardRequestPageModule) },
  { path: 'chequebook-request', loadChildren: () => import('./pages/chequebook-request/chequebook-request.module').then(m => m.ChequebookRequestPageModule) },
  { path: 'report-lost-found', loadChildren: () => import('./pages/report-lost-found/report-lost-found.module').then(m => m.ReportLostFoundPageModule) },
  { path: 'accounts-list', loadChildren: () => import('./pages/accounts-list/accounts-list.module').then(m => m.AccountsListPageModule) },
  { path: 'financing-list', loadChildren: () => import('./pages/financing-list/financing-list.module').then(m => m.FinancingListPageModule) },
  { path: 'cards-list', loadChildren: () => import('./pages/cards-list/cards-list.module').then(m => m.CardsListPageModule) },
  { path: 'chequebook-list', loadChildren: () => import('./pages/chequebook-list/chequebook-list.module').then(m => m.ChequebookListPageModule) },
  { path: 'banker-cheque', loadChildren: () => import('./pages/banker-cheque/banker-cheque.module').then(m => m.BankerChequePageModule) },
  { path: 'demand-draft', loadChildren: () => import('./pages/demand-draft/demand-draft.module').then(m => m.DemandDraftPageModule) },
  { path: 'terms-and-condition', loadChildren: () => import('./pages/information/information.module').then(m => m.InformationPageModule) },
  { path: 'faq', loadChildren: () => import('./pages/information/information.module').then(m => m.InformationPageModule) },
  { path: 'security-statement', loadChildren: () => import('./pages/information/information.module').then(m => m.InformationPageModule) },
  { path: 'ps-theme-creator', loadChildren: () => import('./pages/ps-theme-creator/ps-theme-creator.module').then(m => m.PsThemeCreatorPageModule) },
  { path: 'change-security-questions', loadChildren: () => import('./pages/change-security-questions/change-security-questions.module').then(m => m.ChangeSecurityQuestionsPageModule) },
  { path: 'profile', loadChildren: () => import('./pages/profile/profile.module').then(m => m.ProfilePageModule) },
  { path: 'contact', loadChildren: () => import('./pages/contact/contact.module').then(m => m.ContactPageModule) },
  { path: 'personal-details', loadChildren: () => import('./pages/personal-details/personal-details.module').then(m => m.PersonalDetailsPageModule) },
  { path: 'account-deactivation', loadChildren: () => import('./pages/account-deactivation/account-deactivation.module').then(m => m.AccountDeactivationPageModule) },
  { path: 'credit-card-request', loadChildren: () => import('./pages/credit-card-request/credit-card-request.module').then(m => m.CreditCardRequestPageModule) },
  { path: 'payment', loadChildren: () => import('./pages/payment/payment.module').then(m => m.PaymentPageModule) },
  { path: 'internal-beneficiary', loadChildren: () => import('./pages/internal-beneficiary/internal-beneficiary.module').then(m => m.InternalBeneficiaryPageModule) },
  { path: 'local-beneficiary', loadChildren: () => import('./pages/local-beneficiary/local-beneficiary.module').then(m => m.LocalBeneficiaryPageModule) },
  { path: 'international-beneficiary', loadChildren: () => import('./pages/international-beneficiary/international-beneficiary.module').then(m => m.InternationalBeneficiaryPageModule) },
  { path: 'beneficiary-list', loadChildren: () => import('./pages/beneficiary-list/beneficiary-list.module').then(m => m.BeneficiaryListPageModule) },
  { path: 'lost-document-request', loadChildren: () => import('./pages/lost-document-request/lost-document-request.module').then(m => m.LostDocumentRequestPageModule) },
  { path: 'expired-securities-list', loadChildren: () => import('./pages/expired-securities-list/expired-securities-list.module').then(m => m.ExpiredSecuritiesListPageModule) },
  { path: 'ipo-request', loadChildren: () => import('./pages/ipo-request/ipo-request.module').then(m => m.IpoRequestPageModule) },
  { path: 'security-renewal', loadChildren: () => import('./pages/security-renewal/security-renewal.module').then(m => m.SecurityRenewalPageModule) },
  { path: 'ipo-securities-list', loadChildren: () => import('./pages/ipo-securities-list/ipo-securities-list.module').then(m => m.IpoSecuritiesListPageModule) },
  { path: 'cif-opening', loadChildren: () => import('./pages/cif-opening/cif-opening.module').then(m => m.CifOpeningPageModule) },
  { path: 'financing-payment', loadChildren: () => import('./pages/financing-payment/financing-payment.module').then(m => m.FinancingPaymentPageModule) },
  { path: 'products-services', loadChildren: () => import('./pages/products-services/products-services.module').then(m => m.ProductsServicesPageModule) },
  { path: 'letter-of-guarantee', loadChildren: () => import('./pages/letter-of-guarantee/letter-of-guarantee.module').then(m => m.LetterOfGuaranteePageModule) },
  { path: 'letter-of-credit-request', loadChildren: () => import('./pages/letter-of-credit-request/letter-of-credit-request.module').then(m => m.LetterOfCreditRequestPageModule) },
  { path: 'change-maturity-instructions', loadChildren: () => import('./pages/change-maturity-instructions/change-maturity-instructions.module').then(m => m.ChangeMaturityInstructionsPageModule) },
  { path: 'bulk-payment', loadChildren: () => import('./pages/bulk-payment/bulk-payment.module').then(m => m.BulkPaymentPageModule) },
  { path: 'register-user', loadChildren: () => import('./pages/register-user/register-user.page.module').then(m => m.RegisterUserPageModule) },
  { path: 'users-list', loadChildren: () => import('./pages/users-list/users-list.module').then(m => m.UsersListPageModule) },
  { path: 'on-boarding', loadChildren: () => import('./pages/onboarding/onboarding.module').then(m => m.OnBoardingPageModule) },
  { path: 'national-pooling', loadChildren: () => import('./pages/national-pooling/national-pooling.module').then(m => m.NationalPoolingPageModule) },
  { path: 'pooling-report-page', loadChildren: () => import('./pages/pooling-report-page/pooling-report-page.module').then(m => m.PoolingReportPagePageModule) },
  { path: 'scheduled-transfers-list', loadChildren: () => import('./pages/scheduled-transfers-list/scheduled-transfers-list.module').then(m => m.ScheduledTransfersListPageModule) },
  { path: 'registration-charges', loadChildren: () => import('./pages/registration-charges/registration-charges.page.module').then(m => m.RegistrationChargesPageModule) },
  { path: 'online-bill-payment', loadChildren: () => import('./pages/online-bill-payment/online-bill-payment.module').then(m => m.OnlineBillPaymentPageModule) },
  { path: 'online-bill-payment-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },  
  { path: 'card-management', loadChildren: () => import('./pages/card-management/card-management.page.module').then(m => m.CardManagementPageModule) },
  { path: 'card-pin-request', loadChildren: () => import('./pages/card-pin-request/card-pin-request.page.module').then(m => m.ChangePinPageModule) },
  { path: 'deal-request', loadChildren: () => import('./pages/financial-calculator/financial-calculator.module').then(m => m.FinancialCalculatorPageModule) },
  { path: 'PendingTransfersListPage', loadChildren: () => import('./pages/scheduled-transfers-list/scheduled-transfers-list.module').then(m => m.ScheduledTransfersListPageModule) },
  { path: 'terms-and-conditions-info', loadChildren: () => import('./pages/information/information.module').then(m => m.InformationPageModule) },
  { path: 'security-statement-info', loadChildren: () => import('./pages/information/information.module').then(m => m.InformationPageModule) },
  { path: 'faq-info', loadChildren: () => import('./pages/information/information.module').then(m => m.InformationPageModule) },
  { path: 'pending-transfers-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'account-statement-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'deal-statement-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'facility-statement-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'chequebook-statement-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'card-statement-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'scheduled-transfer-statement-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'financing-calculator-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'exchange-rates-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'security-market-price-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'transfers-list-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'assigned-cifs-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'ipo-request-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'portfolio-position-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'statement-of-transactions-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'renewal-request-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'accounts-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'debit-card-statement-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'credit-card-settlement', loadChildren: () => import('./pages/credit-card-settlement/credit-card-settlement.module').then(m => m.CreditCardSettlementPageModule) },
  { path: 'contact-bank', loadChildren: () => import('./pages/contact-bank/contact-bank.module').then(m => m.ContactBankPageModule) },
  { path: 'letter-of-guarantee-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'letter-of-credit-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'outward-bills-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'letter-of-credit-report-details', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'letter-of-guarantee-report-details', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'outward-bills-report-details', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'outward-bills-report-documents', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'letter-of-credit-report-documents', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'cif-opening-report', loadChildren: () => import('./pages/cif-list-report/cif-list-report.module').then(m => m.ReportCIFListPageModule) },
  { path: 'sukuk-ready-for-renewal-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'ipo-list-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },
  { path: 'my-accounts-standing-order', loadChildren: () => import('./pages/payment/payment.module').then(m => m.PaymentPageModule) },
  { path: 'benef-internal-standing-order', loadChildren: () => import('./pages/payment/payment.module').then(m => m.PaymentPageModule) },
  { path: 'non-benef-internal-standing-order', loadChildren: () => import('./pages/payment/payment.module').then(m => m.PaymentPageModule) },
  { path: 'benef-external-standing-order', loadChildren: () => import('./pages/payment/payment.module').then(m => m.PaymentPageModule) },
  { path: 'non-benef-external-standing-order', loadChildren: () => import('./pages/payment/payment.module').then(m => m.PaymentPageModule) },
  { path: 'interbank-transfer-to-others', loadChildren: () => import('./pages/payment/payment.module').then(m => m.PaymentPageModule) },
  { path: 'zakat-payment', loadChildren: () => import('./pages/payment/payment.module').then(m => m.PaymentPageModule) },
  { path: 'bill-payment', loadChildren: () => import('./pages/payment/payment.module').then(m => m.PaymentPageModule) },
  { path: 'transfer-my-accounts', loadChildren: () => import('./pages/payment/payment.module').then(m => m.PaymentPageModule) },
  { path: 'external-transfer', loadChildren: () => import('./pages/payment/payment.module').then(m => m.PaymentPageModule) },
  { path: 'internal-transfer', loadChildren: () => import('./pages/payment/payment.module').then(m => m.PaymentPageModule) },
  { path: 'local-standing-order', loadChildren: () => import('./pages/payment/payment.module').then(m => m.PaymentPageModule) },
  { path: 'edit-standing-order', loadChildren: () => import('./pages/payment/payment.module').then(m => m.PaymentPageModule) },
  { path: 'sweeping-and-pooling', loadChildren: () => import('./pages/sweeping-and-pooling/sweeping-and-pooling.module').then(m => m.SweepingAndPoolingPageModule) },
  { path: 'activity-log-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) },

  // { path: 'sweeping-list', loadChildren: () => import('./pages/sweeping-list/sweeping-list.module').then(m => m.SweepingListPageModule) },
  /** Added by Hisham.Omar TP# 986400 start
   *  Add new path in order to navigate from the 'transfers list' report to 'Trx Receipt' report.
   */
  { path: 'trx-receipt-report', loadChildren: () => import('./pages/report-page/report-page.module').then(m => m.ReportPagePageModule) }
  /** Added by Hisham.Omar TP# 986400 end */

];

@NgModule({
  imports: [
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules, useHash: true })
  ],
  exports: [RouterModule]
})
export class AppRoutingModule { }
